name: Update
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "v*"
    branches-ignore:
      - "dev"
  schedule:
    - cron: '0 */12 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: CGO_ENABLED=0 go build -o update

      - name: start
        run: |
          chmod 773 update
          ./update

      - name: Commit files
        run: |
          git config --local user.email zhenghongyi1225@foxmail.com
          git config --global user.name action_bot
          git add .
          git commit -m "Auto commit"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
